"""add_resolution_note_and_relationship_created_at

Revision ID: 13a66492027a
Revises: 235ea84e7586
Create Date: 2026-07-17 16:40:47.043986

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13a66492027a'
down_revision: str | Sequence[str] | None = '235ea84e7586'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('governance_issues', sa.Column('resolution_note', sa.Text(), nullable=True))
    op.add_column('relationships', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'created_at')
    op.drop_column('governance_issues', 'resolution_note')
    # ### end Alembic commands ###
